### ISSUE TITLE
В примере не рисуются рамки и штампы

### ISSUE THREAD

**Issue by Rerif** [einhander/eskdx-xelatex#1]
Добрый вечер! При попытке прикрутить eskdx к XeLaTex'у наткнулся на ваш шаблон. Компиляция проходит без критических ошибок и выходной документ компилится, но без рамок и штампа. Использую texLive на win10

**Comment by einhander** [comment]
Добрый вечер. У меня все собирается со штампами и рамками. Если нет рамок, значит есть ошибки при сборке. Прикрепляйте лог.

**Comment by Rerif** [comment]
Итак. Начну сначала. Сначала я пытался скомпилировать шаблон "как есть" но т.к. гост шрифт не хочет подключаться, документ не компилился вообще. Все имеющиеся пакеты обновил, tex-live установлен полный. Заменил шрифт на Times New Roman преамбула стала такой.
```tex
%%% Здесь выбираются необходимые графы
\documentclass[russian,utf8,pointsection,nocolumnsxix,nocolumnxxxi,nocolumnxxxii]{eskdtext}
%%% Что бы работал eskdx и некоторые другие пакеты LaTeX
\usepackage{xecyr}
\setmainfont{Times New Roman}
%%% Для работы шрифтов
\usepackage{xunicode,xltxtra}
%%% Для работы с русскими текстами (расстановки переносов, последовательность комманд строго обязательна)
\usepackage{polyglossia}
\setdefaultlanguage{russian}
%\defaultfontfeatures{Mapping=tex-text}
%%% Для работы со сложными формулами
\usepackage{amsmath}
\usepackage{amssymb}
%%% Что бы использовать символ градуса (°) - \degree
\usepackage{gensymb}
%%% Для переноса составных слов
%\XeTeXinterchartokenstate=1
\XeTeXcharclass `\- 24
\XeTeXinterchartoks 24 0 ={\hskip\z@skip}
\XeTeXinterchartoks 0 24 ={\nobreak}
%%% Ставим подпись к рисункам. Вместо «рис. 1» будет «Рисунок 1»
\addto{\captionsrussian}{\renewcommand{\figurename}{Рисунок}}
%%% Убираем точки после цифр в заголовках
\def\russian@capsformat{%
  \def\postchapter{\@aftersepkern}%
  \def\postsection{\@aftersepkern}%
  \def\postsubsection{\@aftersepkern}%
  \def\postsubsubsection{\@aftersepkern}%
  \def\postparagraph{\@aftersepkern}%
  \def\postsubparagraph{\@aftersepkern}%
}
```
При такой преамбуле документ [компилится](https://drive.google.com/file/d/15wbRApwT_UeEam5MgUznVRhnVekZ8VaH/view?usp=sharing), но без рамок и штампов. Логи для ["как есть"](https://drive.google.com/file/d/1DhnFOV5Hd6BTUN9GIVrsa1TW5xr2XPXx/view?usp=sharing) и с [TNR](https://drive.google.com/file/d/1csoeZ_cCZZfVD92ohSxU0ijDJsklbtr1/view?usp=sharing) прикрепляю.
Судя по всему не рисуются рамки из-за этого:
"
Your \output commands should empty \box255,
e.g., by saying `\shipout\box255'.
Proceed; I'll discard its present contents.
"
Либо шрифт внутри штампов настолько важен, что без него ничего не рисуется.

**Comment by einhander** [comment]
Проверьте свежую версию, у меня подхватывается и TMR и приложенный GOST

**Comment by Rerif** [comment]
Проблема была в сопутствующих пакетах, а если точнее в TexLive, которая должна их подключать. Скорее всего из-за того что TexLive в первую очередь создавался для Linux и он может тянуть пакеты из linux-репозиториев. Решением проблемы было использование MikTex с автоматической загрузкой пакетов.
